name: openiothub_common_pages
description: openiothub_common_pages
version: 0.0.1
author:Farry
homepage:https://github.com/OpenIoTHub

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^0.4.0+3
  openiothub_constants:
    git: https://github.com/OpenIoTHub/openiothub_constants
  openiothub_models:
    git: https://github.com/OpenIoTHub/openiothub_models
  openiothub_plugin:
    git: https://github.com/OpenIoTHub/openiothub_plugin
  #  配网start
  #  esp配网
  #  smartconfig: ^0.0.1
  #  w60x的OneShot配网
  flutter_oneshot:
    git: https://github.com/iotdevice/flutter_oneshot
  # 庆科easylink
  flutter_easylink:
    git: https://github.com/iotdevice/flutter_easylink
  ## 汉枫smartlink
  flutter_smartlink:
    git: https://github.com/iotdevice/flutter_smartlink
  # AirKiss
  airkiss: ^1.0.1
  #  获取wifi名和bssid
  connectivity: ^0.4.8+2
  #  动态请求权限，定位，存储等
  permission_handler: ^3.1.0
  #  配网end
  multicast_dns: ^0.2.2
  mdns_plugin: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
