name: openiothub_common_pages
description: openiothub_common_pages
version: 1.0.5+10
homepage: https://github.com/OpenIoTHub

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^4.0.2
  openiothub_constants: ^1.0.0
  openiothub_api: ^1.0.2+1
  openiothub_grpc_api: ^1.0.2+1
  openiothub_plugin: ^1.0.0+8
#  iot_manager_grpc_api: ^1.0.0
  #  配网start
  #  esp配网
  #  smartconfig: ^0.0.1
  #  w60x的OneShot配网
  flutter_oneshot: ^0.0.1
  # 庆科easylink
  flutter_easylink: ^0.0.1
  ## 汉枫smartlink
  flutter_smartlink: ^0.0.1
  # AirKiss
  airkiss_dart: ^1.0.0
  #  获取wifi名和bssid
  wifi_info_flutter: ^2.0.2
  #  获取当前网络的连接状态
#  connectivity: ^3.0.6
  #  动态请求权限，定位，存储等
  permission_handler: ^10.2.0
  #  配网end
#  fluttertoast: ^8.0.8
  shared_preferences: ^2.1.1
#  fluwx: ^2.4.1
  wechat_kit: ^6.0.1
  image: ^4.0.9
#  flutter_cache_manager: ^2.0.0-nullsafety.1
  url_launcher: ^6.1.11
#  multicast_dns: ^0.3.2+3
  flutter_nsd: ^1.4.0
  oktoast: ^3.3.2+1
  qr_flutter: ^4.1.0
  connectivity_plus: ^5.0.2
#  nsd: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
 assets:
   - assets/images/
   - assets/images/feedback/
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
